"""
Plotting & Analysis Script for KAN-PINN.

This script loads a pre-trained model checkpoint and performs post-training analysis:
1. Loads the model weights and architecture.
2. Computes quantitative metrics (Relative L2 Error) against the exact solution.
3. Generates visualization plots:
   - Solution snapshots at specific time steps (Predicted vs Exact).
   - 2D Contour plot of the solution field u(x,t).
   - Training loss history (log-scale).

Usage:
    python plot_KAN.py --name "Experiment_01"

Author: Group 144 / [Your Name]
Date: 2025
"""

import numpy as np
import os
import argparse
import torch
import sys
from pinn_KAN import PINN

# Import the PINN class from the main model file
try:
    from pinn_KAN import PINN
except ImportError:
    sys.exit("Error: Could not import 'PINN' from 'pinn_KAN.py'. Make sure the file exists.")

def main():
    # 1. Configure argparse
    parser = argparse.ArgumentParser(description='Plotting & Analysis tool for KAN-PINN results')
    parser.add_argument('--name', type=str, default='experiment', 
                        help='Name of the experiment run to load (matches the --name used in train_KAN.py)')
    
    args = parser.parse_args()

    print(f"--- Analyzing Results for Run: {args.name} ---")

    # 2. Initialize the network structure
    # We create a fresh instance of the model structure to load weights into it
    pinn = PINN()

    # Construct the expected model filename
    model_filename = f"{args.name}_model.pth"
    model_path = os.path.join('saved_models', model_filename)
    
    # 3. Load the Trained Model Weights
    if os.path.exists(model_path):
        print(f"Loading model weights from: {model_path}")
        
        # Load weights mapping to the appropriate device (CPU/GPU)
        # This ensures compatibility even if trained on GPU and analyzed on CPU
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        pinn.network.load_state_dict(torch.load(model_path, map_location=device))
        
        # --- COMPUTE L2 ERROR ---
        print("Computing accuracy metrics...")
        try:
            l2_error = pinn.compute_l2_error()
            print(f"\n{'='*40}")
            print(f"   L2 RELATIVE ERROR: {l2_error:.5e}  ({l2_error*100:.2f}%)")
            print(f"{'='*40}\n")
        except AttributeError:
            print("\n[WARNING] Could not compute L2 Error (Ground truth data missing or not loaded).\n")
        except Exception as e:
            print(f"\n[ERROR] Error during L2 computation: {e}\n")
        
        # --- GENERATE SOLUTION PLOTS ---
        # The plot_solution method handles prediction and figure saving internally
        plot_sol_name = f"{args.name}_prediction.png"
        print(f"Generating solution plots -> saved_plots/{plot_sol_name}")
        pinn.plot_solution(name=plot_sol_name)
        
    else:
        print(f"CRITICAL ERROR: Model file not found at {model_path}")
        print("Please check the run name and ensure 'saved_models/' directory exists.")
        return

    # 4. LOCATE AND PLOT LOSS HISTORY
    # We check multiple naming conventions to ensure backward compatibility with older runs
    possible_names = [
        f"loss_{args.name}_model.pth.npy",  # Generated by some versions
        f"loss_{args.name}.npy",            # Clean name format
        "loss_history_KAN.npy",             # Generic fallback name
        "loss_history.npy"                  # Legacy name
    ]
    
    loss_path = None
    for name in possible_names:
        candidate = os.path.join('saved_models', name)
        if os.path.exists(candidate):
            loss_path = candidate
            print(f"Loss history found at: {name}")
            break
    
    plot_loss_name = f"{args.name}_loss.png"

    if loss_path:
        print(f"Generating loss plot -> saved_plots/{plot_loss_name}")
        try:
            loss_history = np.load(loss_path)
            pinn.plot_loss_history(loss_history, name=plot_loss_name)
        except Exception as e:
             print(f"Error reading loss file: {e}")
    else:
        print(f"Warning: No loss history file found. (Checked: {possible_names})")

    print("Analysis complete.")

if __name__ == "__main__":
    main()